# Generated by Django 6.0.2 on 2026-02-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='folio',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Remission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remissions', to='commerce.order')),
            ],
        ),
    ]
