# Generated by Django 6.0.2 on 2026-02-18 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAssigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='commerce.remission')),
            ],
        ),
    ]
