# Generated by Django 6.0.2 on 2026-02-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_creditassigment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditassigment',
            name='remission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='commerce.remission'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.customer'),
        ),
        migrations.AlterField(
            model_name='remission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remissions', to='commerce.order'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='commerce.remission'),
        ),
    ]
