# Generated by Django 6.0.2 on 2026-02-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_creditassigment_remission_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditAssigment',
            new_name='CreditAssingment',
        ),
    ]
