# Generated by Django 6.0.2 on 2026-02-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_rename_creditassigment_creditassingment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditAssingment',
            new_name='CreditAssignment',
        ),
    ]
